package com.matariky.userservice.bean;

import com.baomidou.mybatisplus.annotation.TableName;

import lombok.Data;

@TableName("user_group")
@Data
public class Group  {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.group_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.tenant_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.description
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.create_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.update_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.delete_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.comment
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.created_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.updated_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.id
     *
     * @return the value of user_group.id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.id
     *
     * @param id the value for user_group.id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.group_name
     *
     * @return the value of user_group.group_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.group_name
     *
     * @param groupName the value for user_group.group_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.tenant_id
     *
     * @return the value of user_group.tenant_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.tenant_id
     *
     * @param tenantId the value for user_group.tenant_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.description
     *
     * @return the value of user_group.description
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.description
     *
     * @param description the value for user_group.description
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.create_time
     *
     * @return the value of user_group.create_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.create_time
     *
     * @param createTime the value for user_group.create_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.update_time
     *
     * @return the value of user_group.update_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.update_time
     *
     * @param updateTime the value for user_group.update_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.delete_time
     *
     * @return the value of user_group.delete_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.delete_time
     *
     * @param deleteTime the value for user_group.delete_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.comment
     *
     * @return the value of user_group.comment
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.comment
     *
     * @param comment the value for user_group.comment
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.created_by
     *
     * @return the value of user_group.created_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.created_by
     *
     * @param createdBy the value for user_group.created_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.updated_by
     *
     * @return the value of user_group.updated_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.updated_by
     *
     * @param updatedBy the value for user_group.updated_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

}