package com.matariky.userservice.bean;


import com.baomidou.mybatisplus.annotation.TableName;

import lombok.Data;
@TableName("user_organization")
@Data
public class Organization  {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.organization_code
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String organizationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.organization_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String organizationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.create_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.update_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.description
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.tenant_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.is_virtual
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Boolean isVirtual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.created_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.updated_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.org_type
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Integer orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.order_num
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.comment
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.liaison_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String liaisonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.liaison_mobile
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private String liaisonMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.parent_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization.delete_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    private Long deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.id
     *
     * @return the value of user_organization.id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.id
     *
     * @param id the value for user_organization.id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.organization_code
     *
     * @return the value of user_organization.organization_code
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.organization_code
     *
     * @param organizationCode the value for user_organization.organization_code
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.organization_name
     *
     * @return the value of user_organization.organization_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.organization_name
     *
     * @param organizationName the value for user_organization.organization_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.create_time
     *
     * @return the value of user_organization.create_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.create_time
     *
     * @param createTime the value for user_organization.create_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.update_time
     *
     * @return the value of user_organization.update_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.update_time
     *
     * @param updateTime the value for user_organization.update_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.description
     *
     * @return the value of user_organization.description
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.description
     *
     * @param description the value for user_organization.description
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.tenant_id
     *
     * @return the value of user_organization.tenant_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.tenant_id
     *
     * @param tenantId the value for user_organization.tenant_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.is_virtual
     *
     * @return the value of user_organization.is_virtual
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.is_virtual
     *
     * @param isVirtual the value for user_organization.is_virtual
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.created_by
     *
     * @return the value of user_organization.created_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.created_by
     *
     * @param createdBy the value for user_organization.created_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.updated_by
     *
     * @return the value of user_organization.updated_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.updated_by
     *
     * @param updatedBy the value for user_organization.updated_by
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.org_type
     *
     * @return the value of user_organization.org_type
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.org_type
     *
     * @param orgType the value for user_organization.org_type
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.order_num
     *
     * @return the value of user_organization.order_num
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.order_num
     *
     * @param orderNum the value for user_organization.order_num
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.comment
     *
     * @return the value of user_organization.comment
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.comment
     *
     * @param comment the value for user_organization.comment
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.liaison_name
     *
     * @return the value of user_organization.liaison_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.liaison_name
     *
     * @param liaisonName the value for user_organization.liaison_name
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.liaison_mobile
     *
     * @return the value of user_organization.liaison_mobile
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.liaison_mobile
     *
     * @param liaisonMobile the value for user_organization.liaison_mobile
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.parent_id
     *
     * @return the value of user_organization.parent_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.parent_id
     *
     * @param parentId the value for user_organization.parent_id
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization.delete_time
     *
     * @return the value of user_organization.delete_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization.delete_time
     *
     * @param deleteTime the value for user_organization.delete_time
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

}