package com.matariky.userservice.bean;

import java.util.Map;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.matariky.model.BaseModel;

import lombok.Data;
@TableName("user_permission")
@Data
public class Permission  implements Comparable<Permission>{


    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long origId;


    private Long inSuite;


    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.parent_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.permission_name
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.description
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.tenant_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.create_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.update_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.delete_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.application_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.resource_type
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Integer resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.icon
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.is_active
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.sort_order
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.url
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.created_by
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.updated_by
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.access_type
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Integer accessType;

	@TableField(exist = false)
	private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.resource_attribute
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */
    private Integer resourceAttribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.id
     *
     * @return the value of user_permission.id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.id
     *
     * @param id the value for user_permission.id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.parent_id
     *
     * @return the value of user_permission.parent_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.parent_id
     *
     * @param parentId the value for user_permission.parent_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.permission_name
     *
     * @return the value of user_permission.permission_name
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.permission_name
     *
     * @param permissionName the value for user_permission.permission_name
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.description
     *
     * @return the value of user_permission.description
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.description
     *
     * @param description the value for user_permission.description
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.tenant_id
     *
     * @return the value of user_permission.tenant_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.tenant_id
     *
     * @param tenantId the value for user_permission.tenant_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.create_time
     *
     * @return the value of user_permission.create_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.create_time
     *
     * @param createTime the value for user_permission.create_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.update_time
     *
     * @return the value of user_permission.update_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.update_time
     *
     * @param updateTime the value for user_permission.update_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.delete_time
     *
     * @return the value of user_permission.delete_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.delete_time
     *
     * @param deleteTime the value for user_permission.delete_time
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.application_id
     *
     * @return the value of user_permission.application_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.application_id
     *
     * @param applicationId the value for user_permission.application_id
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.resource_type
     *
     * @return the value of user_permission.resource_type
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.resource_type
     *
     * @param resourceType the value for user_permission.resource_type
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.icon
     *
     * @return the value of user_permission.icon
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.icon
     *
     * @param icon the value for user_permission.icon
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.is_active
     *
     * @return the value of user_permission.is_active
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.is_active
     *
     * @param isActive the value for user_permission.is_active
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.sort_order
     *
     * @return the value of user_permission.sort_order
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.sort_order
     *
     * @param sortOrder the value for user_permission.sort_order
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.url
     *
     * @return the value of user_permission.url
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.url
     *
     * @param url the value for user_permission.url
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.created_by
     *
     * @return the value of user_permission.created_by
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.created_by
     *
     * @param createdBy the value for user_permission.created_by
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.updated_by
     *
     * @return the value of user_permission.updated_by
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.updated_by
     *
     * @param updatedBy the value for user_permission.updated_by
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.access_type
     *
     * @return the value of user_permission.access_type
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.access_type
     *
     * @param accessType the value for user_permission.access_type
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.resource_attribute
     *
     * @return the value of user_permission.resource_attribute
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.resource_attribute
     *
     * @param resourceAttribute the value for user_permission.resource_attribute
     *
     * @mbggenerated Wed Dec 09 11:28:38 CST 2020
     */

	@Override
	public int compareTo(Permission per){
		if(this.sortOrder>per.sortOrder){
			return 1 ;
		}else if(this.sortOrder<per.sortOrder){
			return -1 ;
		}else{
			if(this.id.compareTo(per.id)>0)
				return 1;
			else if (this.id.compareTo(per.id)<0){
				return -1;
			}
			else {
				return 0;
			}
		}
	}
}
