package com.matariky.userservice.bean;

import com.baomidou.mybatisplus.annotation.TableName;

import lombok.Data;

@TableName("user_role")
@Data
public class Role {
      /**
      * 
      */

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.id
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      private Long id;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.tenant_id
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private String tenantId;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.role_name
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private String roleName;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.create_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private Long createTime;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.description
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private String description;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.update_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private Long updateTime;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.delete_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private Long deleteTime;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.comment
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private String comment;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.created_by
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private Long createdBy;

      /**
       * This field was generated by MyBatis Generator.
       * This field corresponds to the database column user_role.updated_by
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */
      private Long updatedBy;

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.id
       *
       * @return the value of user_role.id
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.id
       *
       * @param id the value for user_role.id
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.tenant_id
       *
       * @return the value of user_role.tenant_id
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.tenant_id
       *
       * @param tenantId the value for user_role.tenant_id
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.role_name
       *
       * @return the value of user_role.role_name
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.role_name
       *
       * @param roleName the value for user_role.role_name
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.create_time
       *
       * @return the value of user_role.create_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.create_time
       *
       * @param createTime the value for user_role.create_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.description
       *
       * @return the value of user_role.description
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.description
       *
       * @param description the value for user_role.description
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.update_time
       *
       * @return the value of user_role.update_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.update_time
       *
       * @param updateTime the value for user_role.update_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.delete_time
       *
       * @return the value of user_role.delete_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.delete_time
       *
       * @param deleteTime the value for user_role.delete_time
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.comment
       *
       * @return the value of user_role.comment
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.comment
       *
       * @param comment the value for user_role.comment
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.created_by
       *
       * @return the value of user_role.created_by
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.created_by
       *
       * @param createdBy the value for user_role.created_by
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method returns the value of the database column user_role.updated_by
       *
       * @return the value of user_role.updated_by
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

      /**
       * This method was generated by MyBatis Generator.
       * This method sets the value of the database column user_role.updated_by
       *
       * @param updatedBy the value for user_role.updated_by
       *
       * @mbggenerated Fri Nov 27 16:22:43 CST 2020
       */

}