package com.matariky.userservice.bean;

import java.util.ArrayList;
import java.util.List;

import javax.validation.constraints.NotBlank;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@TableName("user_user")
@Data
public class User {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  @TableField(exist = false)
  List<String> roleNameList;

  @TableField(exist = false)
  List<String> groupNameList;

  @TableField(exist = false)
  List<String> applicationNameLis;

  @TableField(exist = false)
  private List<String> applicationIdList;

  @TableId
  private Long id;

  private String locale;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.login_name
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  // length The longest is 14 English or 7 Chinese characters, only Chinese and
  // English, down lines and numbers, and cannot be all numbers.。
  @NotBlank(message = "The account cannot be empty")
  private String loginName;

  private String theme;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.pazzword
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private String pazzword;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.real_name
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  // @Pattern(regexp="^[\\u4e00-\\u9fa5a-zA-Z0-9_][\\u4e00-\\u9fa5a-zA-Z0-9_]{1,19}$",message="
  // Name 不正确")
  // 只能由数字、字母、中文汉字及下划线组成。 length 为1到20位。
  @NotBlank(message = " Name Can't be empty")
  private String realName;

  // 性别
  private Integer gender;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.cell_phone
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  // 手机号：只能是11位的数字 ,只能是1开头
  @NotBlank(message = "The mobile phone number cannot be empty")
  private String cellPhone;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.email
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private String email;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.create_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Long createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.login_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Long loginTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.last_login_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Long lastLoginTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.login_count
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Integer loginCount;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.update_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Long updateTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.is_active
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Boolean isActive;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.tenant_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  @NotBlank(message = "Tenant cannot be empty")
  private String tenantId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.organization_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Long organizationId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column
   * user_user.self_organization_code
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private String selfOrganizationCode;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column
   * user_user.department_organization_code
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private String departmentOrganizationCode;

  // annotation
  @TableField(exist = false)
  private String uuid;

  @TableField(exist = false)
  private String captcha;

  // A collection of characters
  @TableField(exist = false)
  private List<Long> roleIdList;

  // Local group collection
  @TableField(exist = false)
  private List<Long> groupIdList;

  // Tenant Name
  // tenantName
  @TableField(exist = false)
  private String tenantName;
  // roleName Role Name
  @TableField(exist = false)
  private String roleName;
  // organizationName organize Name
  @TableField(exist = false)
  private String organizationName;

  // Organizational organization -level id
  @TableField(exist = false)
  private Long[] organizationIdList;

  @TableField(exist = false)
  private List<String[]> organizationCodeList;

  public String getOrganizationCodesString() {
    return organizationCodesString;
  }

  public void setOrganizationCodesString(String organizationCodesString) {
    this.setOrganizationCodes(toEmbeddedList(organizationCodesString));
    this.organizationCodesString = organizationCodesString;
  }

  @TableField(exist = false)
  @Getter(AccessLevel.NONE)
  @Setter(AccessLevel.NONE)
  private String organizationCodesString;

  private String orderCode;

  // Personal authority collection
  @TableField(exist = false)
  private List<String[]> organizationCodes;

  private Long createdBy;

  private String userImg;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.delete_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Long deleteTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_user.application_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */
  private Long applicationId;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.id
   *
   * @return the value of user_user.id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.id
   *
   * @param id the value for user_user.id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.login_name
   *
   * @return the value of user_user.login_name
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.login_name
   *
   * @param loginName the value for user_user.login_name
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.pazzword
   *
   * @return the value of user_user.pazzword
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.pazzword
   *
   * @param pazzword the value for user_user.pazzword
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.real_name
   *
   * @return the value of user_user.real_name
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.real_name
   *
   * @param realName the value for user_user.real_name
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.cell_phone
   *
   * @return the value of user_user.cell_phone
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.cell_phone
   *
   * @param cellPhone the value for user_user.cell_phone
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.email
   *
   * @return the value of user_user.email
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.email
   *
   * @param email the value for user_user.email
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.create_time
   *
   * @return the value of user_user.create_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.create_time
   *
   * @param createTime the value for user_user.create_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.login_time
   *
   * @return the value of user_user.login_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.login_time
   *
   * @param loginTime the value for user_user.login_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column
   * user_user.last_login_time
   *
   * @return the value of user_user.last_login_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.last_login_time
   *
   * @param lastLoginTime the value for user_user.last_login_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.login_count
   *
   * @return the value of user_user.login_count
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.login_count
   *
   * @param loginCount the value for user_user.login_count
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.update_time
   *
   * @return the value of user_user.update_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.update_time
   *
   * @param updateTime the value for user_user.update_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.is_active
   *
   * @return the value of user_user.is_active
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.is_active
   *
   * @param isActive the value for user_user.is_active
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.tenant_id
   *
   * @return the value of user_user.tenant_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.tenant_id
   *
   * @param tenantId the value for user_user.tenant_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column
   * user_user.organization_id
   *
   * @return the value of user_user.organization_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.organization_id
   *
   * @param organizationId the value for user_user.organization_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column
   * user_user.self_organization_code
   *
   * @return the value of user_user.self_organization_code
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column
   * user_user.self_organization_code
   *
   * @param selfOrganizationCode the value for user_user.self_organization_code
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column
   * user_user.department_organization_code
   *
   * @return the value of user_user.department_organization_code
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column
   * user_user.department_organization_code
   *
   * @param departmentOrganizationCode the value for
   *                                   user_user.department_organization_code
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.delete_time
   *
   * @return the value of user_user.delete_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.delete_time
   *
   * @param deleteTime the value for user_user.delete_time
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_user.application_id
   *
   * @return the value of user_user.application_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_user.application_id
   *
   * @param applicationId the value for user_user.application_id
   *
   * @mbggenerated Wed Dec 09 11:51:38 CST 2020
   */

  public static List<String[]> toEmbeddedList(String s) {
    if (s == null)
      return null;
    List<String[]> sList = new ArrayList<String[]>();
    String[] chopped = s.split("_");
    for (int i = 1; i < chopped.length; i++) {
      String[] tmpa = new String[i];
      String tmps = chopped[0];
      for (int j = 1; j <= i; j++) {
        tmps = tmps + "_" + chopped[j];
        tmpa[j - 1] = tmps;
      }
      sList.add(tmpa);
    }
    return sList;

  }
}