server:
  port: 9008
  tomcat:
    max-http-form-post-size: 50MB
    threads:
      max: 1000
    max-connections: 6000
context-path: /BootInterceptor
max-http-header-size: 3276800

spring:
  datasource:
    url: jdbc:mysql://172.28.1.12:52189/qslsaasdev?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: matariky
    password: uStack@2022**--**
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    serialization.indent_output: true
  messages:
    basename: i18n/messages
  mvc:
    #favicon:
    enabled: false
  thymeleaf:
    mode: XHTML
    prefix: classpath:/templates/

logging:
  pattern:
    console: "%d - %msg%n"
  file:
    name: d:\amation\logs
  level:
    xaru:
      zsl: debug
    org:
      springfromwork:
        web: info
      hibernate: error

mybatis:
  mapper-locations: classpath:mapper/*.xml
#自定义 Configuration  File
file:
  url: d:\amation\dist
