package com.matariky.userservice.mapper;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.toolkit.Constants;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.matariky.userservice.bean.Group;

public interface GroupMapper extends BaseMapper<Group>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    Group selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int updateByPrimaryKey(Group record);
    
    List<Group> searchByGroupNamePrefix(String tenantId, String groupNamePrefix);

	
	

		@Override
	int insert(Group entity);


	@Override
    int deleteById(Serializable id);


	 @Override
    int deleteByMap(@Param(Constants.COLUMN_MAP) Map<String, Object> columnMap);


	 @Override
    int delete(@Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);

     @Override
    int deleteBatchIds(@Param(Constants.COLLECTION) Collection<? extends Serializable> idList);


	 @Override
    int updateById(@Param(Constants.ENTITY) Group entity);


	 @Override
    int update(@Param(Constants.ENTITY) Group entity, @Param(Constants.WRAPPER) Wrapper<Group> updateWrapper);


	 @Override
    Group selectById(Serializable id);


	 @Override
    List<Group> selectBatchIds(@Param(Constants.COLLECTION) Collection<? extends Serializable> idList);


	 @Override
    List<Group> selectByMap(@Param(Constants.COLUMN_MAP) Map<String, Object> columnMap);


	 @Override
    Group selectOne(@Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);


	 @Override
    Long selectCount(@Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);


	 @Override
    List<Group> selectList(@Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);


	@Override
    List<Map<String, Object>> selectMaps(@Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);


	 @Override
    List<Object> selectObjs(@Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);


    Page<Group> selectPage(Page<Group> page, @Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);

    Page<Map<String, Object>> selectMapsPage(Page<Group> page, @Param(Constants.WRAPPER) Wrapper<Group> queryWrapper);

	
	
}
