package com.matariky.userservice.mapper;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.toolkit.Constants;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.matariky.userservice.bean.Role;

public interface RoleMapper extends BaseMapper<Role>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int updateByPrimaryKey(Role record);

    	@Override
	int insert(Role entity);


	@Override
    int deleteById(Serializable id);


	 @Override
    int deleteByMap(@Param(Constants.COLUMN_MAP) Map<String, Object> columnMap);


	 @Override
    int delete(@Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);

     @Override
    int deleteBatchIds(@Param(Constants.COLLECTION) Collection<? extends Serializable> idList);


	 @Override
    int updateById(@Param(Constants.ENTITY) Role entity);


	 @Override
    int update(@Param(Constants.ENTITY) Role entity, @Param(Constants.WRAPPER) Wrapper<Role> updateWrapper);


	 @Override
    Role selectById(Serializable id);


	 @Override
    List<Role> selectBatchIds(@Param(Constants.COLLECTION) Collection<? extends Serializable> idList);


	 @Override
    List<Role> selectByMap(@Param(Constants.COLUMN_MAP) Map<String, Object> columnMap);


	 @Override
    Role selectOne(@Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);


	 @Override
    Long selectCount(@Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);


	 @Override
    List<Role> selectList(@Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);


	@Override
    List<Map<String, Object>> selectMaps(@Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);


	 @Override
    List<Object> selectObjs(@Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);


    Page<Role> selectPage(Page<Role> page, @Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);

    Page<Map<String, Object>> selectMapsPage(Page<Role> page, @Param(Constants.WRAPPER) Wrapper<Role> queryWrapper);
}
