package com.matariky.userservice.mapper;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.toolkit.Constants;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.matariky.userservice.bean.Tenant;

public interface TenantMapper extends BaseMapper<Tenant>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tenant
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tenant
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int insertSelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tenant
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    Tenant selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tenant
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int updateByPrimaryKeySelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tenant
     *
     * @mbggenerated Fri Nov 27 16:22:43 CST 2020
     */
    int updateByPrimaryKey(Tenant record);
    
    @Override
    Tenant selectById(Serializable id);

    	@Override
	int insert(Tenant entity);


	@Override
    int deleteById(Serializable id);


	 @Override
    int deleteByMap(@Param(Constants.COLUMN_MAP) Map<String, Object> columnMap);


	 @Override
    int delete(@Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);

     @Override
    int deleteBatchIds(@Param(Constants.COLLECTION) Collection<? extends Serializable> idList);


	 @Override
    int updateById(@Param(Constants.ENTITY) Tenant entity);


	 @Override
    int update(@Param(Constants.ENTITY) Tenant entity, @Param(Constants.WRAPPER) Wrapper<Tenant> updateWrapper);




	 @Override
    List<Tenant> selectBatchIds(@Param(Constants.COLLECTION) Collection<? extends Serializable> idList);


	 @Override
    List<Tenant> selectByMap(@Param(Constants.COLUMN_MAP) Map<String, Object> columnMap);


	 @Override
    Tenant selectOne(@Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);


	 @Override
    Long selectCount(@Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);


	 @Override
    List<Tenant> selectList(@Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);


	@Override
    List<Map<String, Object>> selectMaps(@Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);


	 @Override
    List<Object> selectObjs(@Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);


    Page<Tenant> selectPage(Page<Tenant> page, @Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);

    Page<Map<String, Object>> selectMapsPage(Page<Tenant> page, @Param(Constants.WRAPPER) Wrapper<Tenant> queryWrapper);
     
    Tenant selectBytenantCode(String tenantCode);
     
}
